name: McTest
version: "${version}"
main: fr.traqueur.mctest.McTestPlugin
api-version: "1.21"
description: Example plugin demonstrating Structura config read/write
authors: [ Traqueur ]

commands:
  mctest:
    description: McTest main command
    usage: /mctest <reload|save|info>
    permission: mctest.admin
